name: 8earDockerCI
on:
  push:
    branches:
    - master
  schedule:
    - cron:  '0 0 0 * *'
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Push to dockerhub and github registry
      run: |
        ./make.sh